development:
  adapter: mysql2
  database: racing_on_rails_development_3
  username: ror_development
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

acceptance:
  adapter: mysql2
  database: racing_on_rails_test_3
  username: ror_test
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

test:
  adapter: mysql2
  database: racing_on_rails_test_3
  username: ror_test
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

production:
  adapter: mysql2
  database: racing_on_rails_production_3
  username: root
  encoding: utf8
  host: localhost
  reconnect: false
  pool: 5
